// <auto-generated />
using System;
using DataAnalysisAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAnalysisAPI.Migrations
{
    [DbContext(typeof(DataAnalysisDbContext))]
    partial class DataAnalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAnalysisAPI.Models.SalarySpendDetailsDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentWithLargestSalary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartmentWithSmallestSalary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LargestSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SmallestSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSpend")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SalarySpendDetailsDailies");
                });
#pragma warning restore 612, 618
        }
    }
}
